name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Новые возможности'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Исправления'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Поддержка'
    labels:
      - 'chore'
      - 'dependencies'
      - 'maintenance'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Изменения
  
  $CHANGES
  
  ## Авторы
  
  $CONTRIBUTORS

