version: '3.8'

services:
  eva-lawyer-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eva-lawyer-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./tmp:/app/tmp
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
